# Generated by Django 3.1.5 on 2021-04-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
