# Generated by Django 3.1.5 on 2021-04-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=100)),
                ('feed', models.CharField(max_length=10)),
                ('cityname', models.CharField(max_length=40)),
                ('mcity', models.CharField(max_length=50)),
            ],
        ),
    ]
